// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/Doctor/detailsDate" | "/Doctor/homeDoctor" | "/Doctor/prescription" | "/Patient/datailsDate" | "/Patient/dates" | "/Patient/home" | "/Patient/landingPage" | "/Patient/login" | "/Patient/paymentRecord" | "/Patient/profile" | "/Patient/register" | "/Receptionist/dates" | "/Receptionist/datingStatusLog" | "/Receptionist/doctorPatientLog" | "/Receptionist/doctors" | "/Receptionist/farmacy" | "/Receptionist/home" | "/Receptionist/patients" | "/Receptionist/registerEmployee" | "/Receptionist/registerRecep" | "/Receptionist/tickests"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/Doctor/detailsDate": {}
  "/Doctor/homeDoctor": {}
  "/Doctor/prescription": {}
  "/Patient/datailsDate": {}
  "/Patient/dates": {}
  "/Patient/home": {}
  "/Patient/landingPage": {}
  "/Patient/login": {}
  "/Patient/paymentRecord": {}
  "/Patient/profile": {}
  "/Patient/register": {}
  "/Receptionist/dates": {}
  "/Receptionist/datingStatusLog": {}
  "/Receptionist/doctorPatientLog": {}
  "/Receptionist/doctors": {}
  "/Receptionist/farmacy": {}
  "/Receptionist/home": {}
  "/Receptionist/patients": {}
  "/Receptionist/registerEmployee": {}
  "/Receptionist/registerRecep": {}
  "/Receptionist/tickests": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
