// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../../app/Doctor/detailsDate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Doctor/detailsDate">> = Specific
  const handler = {} as typeof import("../../../app/Doctor/detailsDate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Doctor/homeDoctor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Doctor/homeDoctor">> = Specific
  const handler = {} as typeof import("../../../app/Doctor/homeDoctor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Doctor/prescription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Doctor/prescription">> = Specific
  const handler = {} as typeof import("../../../app/Doctor/prescription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Patient/datailsDate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Patient/datailsDate">> = Specific
  const handler = {} as typeof import("../../../app/Patient/datailsDate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Patient/dates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Patient/dates">> = Specific
  const handler = {} as typeof import("../../../app/Patient/dates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Patient/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Patient/home">> = Specific
  const handler = {} as typeof import("../../../app/Patient/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Patient/landingPage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Patient/landingPage">> = Specific
  const handler = {} as typeof import("../../../app/Patient/landingPage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Patient/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Patient/login">> = Specific
  const handler = {} as typeof import("../../../app/Patient/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Patient/paymentRecord/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Patient/paymentRecord">> = Specific
  const handler = {} as typeof import("../../../app/Patient/paymentRecord/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Patient/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Patient/profile">> = Specific
  const handler = {} as typeof import("../../../app/Patient/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Patient/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Patient/register">> = Specific
  const handler = {} as typeof import("../../../app/Patient/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Receptionist/dates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Receptionist/dates">> = Specific
  const handler = {} as typeof import("../../../app/Receptionist/dates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Receptionist/datingStatusLog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Receptionist/datingStatusLog">> = Specific
  const handler = {} as typeof import("../../../app/Receptionist/datingStatusLog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Receptionist/doctorPatientLog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Receptionist/doctorPatientLog">> = Specific
  const handler = {} as typeof import("../../../app/Receptionist/doctorPatientLog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Receptionist/doctors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Receptionist/doctors">> = Specific
  const handler = {} as typeof import("../../../app/Receptionist/doctors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Receptionist/farmacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Receptionist/farmacy">> = Specific
  const handler = {} as typeof import("../../../app/Receptionist/farmacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Receptionist/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Receptionist/home">> = Specific
  const handler = {} as typeof import("../../../app/Receptionist/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Receptionist/patients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Receptionist/patients">> = Specific
  const handler = {} as typeof import("../../../app/Receptionist/patients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Receptionist/registerEmployee/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Receptionist/registerEmployee">> = Specific
  const handler = {} as typeof import("../../../app/Receptionist/registerEmployee/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Receptionist/registerRecep/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Receptionist/registerRecep">> = Specific
  const handler = {} as typeof import("../../../app/Receptionist/registerRecep/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/Receptionist/tickests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/Receptionist/tickests">> = Specific
  const handler = {} as typeof import("../../../app/Receptionist/tickests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
